import { ChatSession, ChatMessage } from "./gemini";
export type { ChatSession, ChatMessage };
import { jsPDF } from "jspdf";

const STORAGE_KEYS = {
  CHATS: "aura_chats",
  SETTINGS: "aura_settings",
  PROFILE: "aura_profile",
};

export interface UserProfile {
  name: string;
  avatar?: string;
  bio?: string;
}

export interface AppSettings {
  theme: "dark" | "light";
  fontSize: "sm" | "md" | "lg";
  voiceEnabled: boolean;
}

export const Storage = {
  getChats: (): ChatSession[] => {
    const data = localStorage.getItem(STORAGE_KEYS.CHATS);
    return data ? JSON.parse(data) : [];
  },

  saveChats: (chats: ChatSession[]) => {
    localStorage.setItem(STORAGE_KEYS.CHATS, JSON.stringify(chats));
  },

  addMessageToChat: (chatId: string, message: ChatMessage) => {
    const chats = Storage.getChats();
    const chatIndex = chats.findIndex((c) => c.id === chatId);
    if (chatIndex !== -1) {
      chats[chatIndex].messages.push(message);
      chats[chatIndex].lastUpdate = Date.now();
      Storage.saveChats(chats);
    }
  },

  createChat: (module: string = "general"): ChatSession => {
    const newChat: ChatSession = {
      id: crypto.randomUUID(),
      title: "New Chat",
      messages: [],
      lastUpdate: Date.now(),
      module,
    };
    const chats = Storage.getChats();
    Storage.saveChats([newChat, ...chats]);
    return newChat;
  },

  getProfile: (): UserProfile => {
    const data = localStorage.getItem(STORAGE_KEYS.PROFILE);
    return data ? JSON.parse(data) : { name: "Guest User" };
  },

  saveProfile: (profile: UserProfile) => {
    localStorage.setItem(STORAGE_KEYS.PROFILE, JSON.stringify(profile));
  },

  getSettings: (): AppSettings => {
    const data = localStorage.getItem(STORAGE_KEYS.SETTINGS);
    return data ? JSON.parse(data) : { theme: "dark", fontSize: "md", voiceEnabled: true };
  },

  saveSettings: (settings: AppSettings) => {
    localStorage.setItem(STORAGE_KEYS.SETTINGS, JSON.stringify(settings));
  },

  exportToPDF: (session: ChatSession) => {
    const doc = new jsPDF();
    let y = 20;
    
    doc.setFontSize(20);
    doc.text(`Chat History: ${session.title}`, 20, y);
    y += 15;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by Aura AI | ${new Date(session.lastUpdate).toLocaleString()}`, 20, y);
    y += 15;

    session.messages.forEach((msg) => {
      doc.setFontSize(10);
      if (msg.role === "user") {
        doc.setTextColor(14, 165, 233); // Aura 500
      } else {
        doc.setTextColor(100, 100, 100);
      }
      doc.text(`${msg.role.toUpperCase()}:`, 20, y);
      y += 6;

      doc.setTextColor(0);
      doc.setFontSize(10);
      
      const text = msg.parts.map(p => p.text || "[Image/Media]").join("\n");
      const splitText = doc.splitTextToSize(text, 160);
      
      splitText.forEach((line: string) => {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 20, y);
        y += 6;
      });
      
      y += 5;
    });

    doc.save(`aura-chat-${session.id.slice(0, 8)}.pdf`);
  },
};
